### ISSUE TITLE
Error when trying to use fp.to_dataframe() for a single PDB structure

### ISSUE THREAD

**Issue by SampurnaM** [chemosim-lab/ProLIF#192]
Hi.
I am trying to get interaction fingerprint for a pair of proteins, from the PDB file with the structure of the complex.
I have created two mol files, after loading them into MDA.
`hla_selection_prolif = ("resid 1:276 or resid 462:561 or resid 1261:1269")
hla_a1101_pdb_plf = a1101_pdb.select_atoms(hla_selection_prolif)
a1101_hla_mol = plf.Molecule.from_mda(hla_a1101_pdb_plf )`  ( and similarly for antibody)

### Problem
From the documentation, I thought fp.generate() should be used for single structures. It runs, and prints out all the information, but I can't call fp.to_dataframe or plot interactions. I have tried to use fp.run_from_iterable as well.

**Here is what I have tried so far, and the errors:**
`fp.generate(a1101_ab_mol,a1101_hla_mol,metadata=True)`
#### Output: Truncated here for clarity
`{(ResidueId(TYR, 663, C), ResidueId(GLU, 498, B)): {'VdWContact': ({'indices': {'ligand': (11,), 'protein': (8,)}, 'parent_indices': {'ligand': (459,), 'protein': (4937,)}, 'distance': 2.5766485145069233},)}, (ResidueId(TYR, 664, C), ResidueId(ASP, 40, A)): {'HBDonor': ({'indices': {'(ResidueId(TRP, 1055, D), ResidueId(GLY, 17, A)): {'HBDonor': ({'indices': {'ligand': (10, 19), 'protein': (3,)}, 'parent_indices': {'ligand': (4828, 4837), 'protein': (262,)}, 'distance': 3.155431200194604, 'DHA_angle': 158.46289346537824},), 'VdWContact': ({'indices': {'ligand': (19,), 'protein': (3,)}, 'parent_indices': {'ligand': (4837,), 'protein': (262,)}, 'distance': 2.2091385396444876},)}}`
### Error 1:
plf.to_dataframe(ifp, fp.interactions)
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[105], line 1
----> 1 plf.to_dataframe(ifp, fp.interactions)

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/prolif/utils.py:288, in to_dataframe(ifp, interactions, count, dtype, drop_empty, index_col)
    280     return pd.DataFrame([], index=index)
    281 values = np.array(
    282     [
    283         np.hstack([bitvector_list[frame] for bitvector_list in data.values()])
    284         for frame in range(len(index))
    285     ]
    286 )
    287 columns = pd.MultiIndex.from_tuples(
--> 288     [
    289         (str(lig_res), str(prot_res), i)
    290         for lig_res, prot_res in residue_pairs
    291         for i in interactions
    292     ],
    293     names=["ligand", "protein", "interaction"],
    294 )
    295 df = pd.DataFrame(values, columns=columns, index=index)
    296 df = df.astype(dtype)

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/prolif/utils.py:290, in <listcomp>(.0)
    280     return pd.DataFrame([], index=index)
    281 values = np.array(
    282     [
    283         np.hstack([bitvector_list[frame] for bitvector_list in data.values()])
    284         for frame in range(len(index))
    285     ]
    286 )
    287 columns = pd.MultiIndex.from_tuples(
    288     [
    289         (str(lig_res), str(prot_res), i)
--> 290         for lig_res, prot_res in residue_pairs
    291         for i in interactions
    292     ],
    293     names=["ligand", "protein", "interaction"],
    294 )
    295 df = pd.DataFrame(values, columns=columns, index=index)
    296 df = df.astype(dtype)

ValueError: too many values to unpack (expected 2)
```
#### Attempts to solve it: 1
 plf.to_dataframe(ifp) # fp.interactions
`TypeError: to_dataframe() missing 1 required positional argument: 'interactions'`
#### Attempts to solve it: 2
plf.to_dataframe(fp.interactions)#ifp
`TypeError: to_dataframe() missing 1 required positional argument: 'interactions'`
### Attempts to use run_from_iterable
result = fp.run_from_iterable(a1101_ab_mol,a1101_hla_mol)
```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/sampurna/anaconda3/envs/prolif/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/sampurna/anaconda3/envs/prolif/lib/python3.10/site-packages/prolif/parallel.py", line 233, in executor
    return cls.fp.generate(mol, cls.pmol, residues=cls.residues, metadata=True)
  File "/home/sampurna/anaconda3/envs/prolif/lib/python3.10/site-packages/prolif/fingerprint.py", line 363, in generate
    for lresid, lres in lig.residues.items():
AttributeError: 'Residue' object has no attribute 'residues'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
Cell In[101], line 1
----> 1 result = fp.run_from_iterable(a1101_ab_mol,a1101_hla_mol)

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/prolif/fingerprint.py:596, in Fingerprint.run_from_iterable(self, lig_iterable, prot_mol, residues, progress, n_jobs)
    594     residues = list(prot_mol.residues)
    595 if n_jobs != 1:
--> 596     return self._run_iter_parallel(
    597         lig_iterable=lig_iterable,
    598         prot_mol=prot_mol,
    599         residues=residues,
    600         progress=progress,
    601         n_jobs=n_jobs,
    602     )
    604 iterator = tqdm(lig_iterable) if progress else lig_iterable
    605 ifp = {}

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/prolif/fingerprint.py:629, in Fingerprint._run_iter_parallel(self, lig_iterable, prot_mol, residues, progress, n_jobs)
    620 ifp = {}
    622 with MolIterablePool(
    623     n_jobs,
    624     fingerprint=self,
   (...)
    627     tqdm_kwargs={"total": total, "disable": not progress},
    628 ) as pool:
--> 629     for i, ifp_data in enumerate(pool.process(lig_iterable)):
    630         ifp[i] = ifp_data
    632 self.ifp = ifp

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/tqdm/notebook.py:249, in tqdm_notebook.__iter__(self)
    247 try:
    248     it = super(tqdm_notebook, self).__iter__()
--> 249     for obj in it:
    250         # return super(tqdm...) will not catch exception
    251         yield obj
    252 # NB: except ... [ as ...] breaks IPython async KeyboardInterrupt

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/tqdm/std.py:1182, in tqdm.__iter__(self)
   1179 time = self._time
   1181 try:
-> 1182     for obj in iterable:
   1183         yield obj
   1184         # Update and possibly print the progressbar.
   1185         # Note: does not call self.update(1) for speed optimisation.

File ~/anaconda3/envs/prolif/lib/python3.10/site-packages/multiprocess/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

AttributeError: 'Residue' object has no attribute 'residues'
```
Am I missing something very obvious?

Sampurna

**Comment by cbouy** [comment]
Hi @SampurnaM, please follow the [PDB tutorial](https://prolif.readthedocs.io/en/stable/notebooks/pdb.html#pdb) to run the tool with a PDB file.
Happy to answer any remaining questions after that!

**Comment by SampurnaM** [comment]
Hi Cedric, apologies: the step I did incorrectly was not putting the ligand_mol inside [] when running fp.run_from_iterable. I thought that is for multiple poses from a docked PDB file, and I had only a single pose.

Thanks for the timely advice!
Sampurna
