### ISSUE TITLE
Error on fp.to_dataframe()

### ISSUE THREAD

**Issue by ale94mleon** [chemosim-lab/ProLIF#44]
Hi, in one part of the code I have:
``` python
ligand = u.atoms.select_atoms("resname LIA")
prot = u.atoms.select_atoms("protein")

fp = plf.Fingerprint()
fp.run(u.trajectory[::1500], ligand, prot)
fp_df = fp.to_dataframe()
```
And the output: 
Fisrt some warning pops up during the fp.run(), but finally ends.
```
  0%|                                                                                                                                       | 0/2 [00:00<?, ?it/s]
/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/MDAnalysis/converters/RDKit.py:975: UserWarning: The standardization could not be completed within a reasonable number of iterations
  warnings.warn("The standardization could not be completed within a "
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:50<00:00, 25.40s/it]
```
And then
```
Traceback (most recent call last):
  File "/home/ale/MY_PYTHON_PACKEGES/mdynamic/tools/tools.py", line 814, in <module>
    a = classifier(tpr, xtc, ligand, elapsed_steps = 2000, load_fingerprint = False, fingerprint_files = ['fp.pkl', 'fp_atoms.pkl'], n_clusters = 2)
  File "/home/ale/MY_PYTHON_PACKEGES/mdynamic/tools/tools.py", line 764, in classifier
    fp_df = fp.to_dataframe()
  File "/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/prolif/fingerprint.py", line 475, in to_dataframe
    return to_dataframe(self.ifp, self.interactions.keys(), **kwargs)
  File "/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/prolif/utils.py", line 207, in to_dataframe
    is_atompair = isinstance(ifp[0][k][0], Iterable)
KeyError: (ResidueId(LIA, 510, A), ResidueId(ALA, 233, A))
```
Any idea?
Thanks in advance!

**Comment by cbouy** [comment]
That's odd! Can you provide the output of the following commands please ?
- `print(fp.ifp[0])`
- `print(sorted(set([k for d in fp.ifp for k in d.keys() if k != "Frame"])))`

**Comment by ale94mleon** [comment]
This is the output:
```
  0%|                                                                                                                                       | 0/2 [00:00<?, ?it/s/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/MDAnalysis/converters/RDKit.py:975: UserWarning: The standardization could not be completed within a reasonable number of iterations
  warnings.warn("The standardization could not be completed within a "
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:53<00:00, 26.98s/it]
{'Frame': 0}
[(ResidueId(LIA, 510, A), ResidueId(TYR, 31, A)), (ResidueId(LIA, 510, A), ResidueId(LYS, 35, A)), (ResidueId(LIA, 510, A), ResidueId(ALA, 50, A)), (ResidueId(LIA, 510, A), ResidueId(VAL, 54, A)), (ResidueId(LIA, 510, A), ResidueId(CYS, 57, A)), (ResidueId(LIA, 510, A), ResidueId(ALA, 58, A)), (ResidueId(LIA, 510, A), ResidueId(PHE, 90, A)), (ResidueId(LIA, 510, A), ResidueId(PRO, 91, A)), (ResidueId(LIA, 510, A), ResidueId(ALA, 93, A)), (ResidueId(LIA, 510, A), ResidueId(PHE, 94, A)), (ResidueId(LIA, 510, A), ResidueId(MET, 95, A)), (ResidueId(LIA, 510, A), ResidueId(CYS, 96, A)), (ResidueId(LIA, 510, A), ResidueId(ILE, 97, A)), (ResidueId(LIA, 510, A), ResidueId(ILE, 98, A)), (ResidueId(LIA, 510, A), ResidueId(CYS, 99, A)), (ResidueId(LIA, 510, A), ResidueId(GLY, 101, A)), (ResidueId(LIA, 510, A), ResidueId(SER, 102, A)), (ResidueId(LIA, 510, A), ResidueId(ASP, 103, A)), (ResidueId(LIA, 510, A), ResidueId(LEU, 104, A)), (ResidueId(LIA, 510, A), ResidueId(PHE, 105, A)), (ResidueId(LIA, 510, A), ResidueId(THR, 106, A)), (ResidueId(LIA, 510, A), ResidueId(GLY, 107, A)), (ResidueId(LIA, 510, A), ResidueId(ASN, 108, A)), (ResidueId(LIA, 510, A), ResidueId(ALA, 111, A)), (ResidueId(LIA, 510, A), ResidueId(VAL, 196, A)), (ResidueId(LIA, 510, A), ResidueId(CYS, 197, A)), (ResidueId(LIA, 510, A), ResidueId(ALA, 199, A)), (ResidueId(LIA, 510, A), ResidueId(VAL, 200, A)), (ResidueId(LIA, 510, A), ResidueId(VAL, 203, A)), (ResidueId(LIA, 510, A), ResidueId(LEU, 204, A)), (ResidueId(LIA, 510, A), ResidueId(VAL, 220, A)), (ResidueId(LIA, 510, A), ResidueId(PHE, 223, A)), (ResidueId(LIA, 510, A), ResidueId(HIS, 230, A)), (ResidueId(LIA, 510, A), ResidueId(ILE, 232, A)), (ResidueId(LIA, 510, A), ResidueId(ALA, 233, A))]
Traceback (most recent call last):
  File "/home/ale/MY_PYTHON_PACKEGES/mdynamic/tools/tools.py", line 815, in <module>
    a = classifier(tpr, xtc, ligand, elapsed_steps = 2000, load_fingerprint = False, fingerprint_files = ['fp.pkl', 'fp_atoms.pkl'], n_clusters = 2)
  File "/home/ale/MY_PYTHON_PACKEGES/mdynamic/tools/tools.py", line 765, in classifier
    fp_df = fp.to_dataframe()
  File "/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/prolif/fingerprint.py", line 475, in to_dataframe
    return to_dataframe(self.ifp, self.interactions.keys(), **kwargs)
  File "/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/prolif/utils.py", line 207, in to_dataframe
    is_atompair = isinstance(ifp[0][k][0], Iterable)
KeyError: (ResidueId(LIA, 510, A), ResidueId(ALA, 233, A))
```
I create my universe from a .tpr and an .xtc files (GROMACS simulation). I got the following warnings messages:
```
/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/MDAnalysis/topology/PDBParser.py:332: UserWarning: Unknown element  found for some atoms. These have been given an empty element record. If needed they can be guessed using MDAnalysis.topology.guessers.
  warnings.warn(wmsg)
/home/ale/anaconda3/envs/mdynamic/lib/python3.9/site-packages/MDAnalysis/topology/guessers.py:146: UserWarning: Failed to guess the mass for the following atom types: 
  warnings.warn("Failed to guess the mass for the following atom types: {}".format(atom_type))
```
Therefore I needed to use `u.add_TopologyAttr` for *elements*, *types*, *resid* and *chainID*. And I think that with these the warnings were fixed.

**Comment by cbouy** [comment]
Ok, the problem was because no interaction is detected in the first frame.
I just published a quick fix, can you reinstall prolif with `pip install git+https://github.com/chemosim-lab/ProLIF.git` and run your code again?

Don't forget to close the issue if it worked.

Thanks,
Cédric

**Comment by ale94mleon** [comment]
Excellent! Now is working. Thanks a lot!
